### ISSUE TITLE
Add to PyPI

### ISSUE THREAD

**Issue by kawindme** [ahaselsteiner/viroconcom#4]
Add viroconcom to PyPI - the Python Package Index.

**Comment by ahaselsteiner** [comment]
Done. 

viroconcom at PyPI:
![image](https://user-images.githubusercontent.com/11452055/41166633-0d1df472-6b41-11e8-8a1f-70ea3f05df25.png)

Installed viroconcom with pip install at Heroku:

![image](https://user-images.githubusercontent.com/11452055/41166705-426ad06e-6b41-11e8-9324-c93854bf79a3.png)
